/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Veiculo;

import DAO.VeiculoDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Veiculo;
import views.Home;


/**
 *
 * @author rober
 */
public class GerenciarVeiculos extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarVeiculos
     */
    public GerenciarVeiculos() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tVeiculo.getModel();
        tVeiculo.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) tVeiculo.getModel();
        modelo.setNumRows(0);
        VeiculoDAO vdao = new VeiculoDAO();

        for (Veiculo v : vdao.read()) {

            modelo.addRow(new Object[]{
                v.getId(),
                v.getModelo(),
                v.getAno(),
                v.getChassis(),
                v.getValorDiaria(),
                v.getCapacidade(),
                v.getCombustivel(),
                v.getMarca()             
                
            });

        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        botaoExcluir = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        botaoVoltarTelaHome = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tVeiculo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botaoAtualizar = new javax.swing.JButton();
        txtChassis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtVDiaria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCapacidade = new javax.swing.JTextField();
        txtCombustivel = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtAno = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CLIENTES");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img/excluir.png"))); // NOI18N
        botaoExcluir.setToolTipText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(botaoExcluir);
        botaoExcluir.setBounds(330, 280, 95, 50);

        botaoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img/novo-arquivo.png"))); // NOI18N
        botaoCadastrar.setToolTipText("Cadastrar novo veiculo");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrar);
        botaoCadastrar.setBounds(460, 280, 104, 50);

        botaoVoltarTelaHome.setText("Voltar");
        botaoVoltarTelaHome.setToolTipText("Voltar a tela anterior");
        botaoVoltarTelaHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarTelaHomeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltarTelaHome);
        botaoVoltarTelaHome.setBounds(760, 580, 71, 23);

        tVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "modelo", "ano", "chassis", "valorDiaria", "capacidade", "combustivel", "marca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tVeiculoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tVeiculo);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 90, 830, 169);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VEÍCULOS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(382, 22, 124, 29);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(351, 57, 190, 10);

        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img/atualizada.png"))); // NOI18N
        botaoAtualizar.setToolTipText("Atualizar");
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAtualizar);
        botaoAtualizar.setBounds(640, 440, 60, 40);

        txtChassis.setToolTipText("Chassis do veículo");
        getContentPane().add(txtChassis);
        txtChassis.setBounds(140, 500, 159, 22);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Combustivel: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 450, 90, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Valor da Diária:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 550, 90, 16);

        txtModelo.setToolTipText("Ex: Civic, Uno, Palio");
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        getContentPane().add(txtModelo);
        txtModelo.setBounds(140, 400, 157, 22);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Marca:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 500, 50, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modelo:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 400, 50, 16);

        txtVDiaria.setToolTipText("Valor da diária do veículo");
        txtVDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVDiariaActionPerformed(evt);
            }
        });
        getContentPane().add(txtVDiaria);
        txtVDiaria.setBounds(140, 550, 76, 22);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ano:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 450, 40, 16);

        txtCapacidade.setToolTipText("Capacidade de ocupantes");
        getContentPane().add(txtCapacidade);
        txtCapacidade.setBounds(480, 400, 73, 20);

        txtCombustivel.setToolTipText("Ex: Gasolina, Etanol");
        getContentPane().add(txtCombustivel);
        txtCombustivel.setBounds(480, 450, 100, 20);

        txtMarca.setToolTipText("Ex: Fiat, Toyota");
        getContentPane().add(txtMarca);
        txtMarca.setBounds(480, 500, 101, 20);

        try {
            txtAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAno.setToolTipText("Ano do veículo");
        getContentPane().add(txtAno);
        txtAno.setBounds(140, 450, 82, 22);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Capacidade:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 400, 70, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Chassis:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 500, 50, 16);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img/fundo-Carro.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-10, 10, 910, 640);

        setSize(new java.awt.Dimension(881, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarTelaHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarTelaHomeActionPerformed
        Home voltarTelaHome = new Home();
        voltarTelaHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarTelaHomeActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        if (tVeiculo.getSelectedRow() != -1) {
            int id = (int) tVeiculo.getValueAt(tVeiculo.getSelectedRow(), 0);
            String modelo = txtModelo.getText();
            String ano = txtAno.getText();
            String chassis = txtChassis.getText();
            String valorDiaria = txtVDiaria.getText();
            String capacidade = txtCapacidade.getText();
            String combustivel = txtCombustivel.getText();
            String marca = txtMarca.getText();  

            Veiculo veiculo = new Veiculo(modelo, ano, chassis, valorDiaria, capacidade,combustivel, marca, id);
            VeiculoDAO c = new VeiculoDAO();

            c.deletar(veiculo);

            txtModelo.setText("");
            txtAno.setText("");
            txtChassis.setText("");
            txtVDiaria.setText("");
            txtCapacidade.setText("");
            txtCombustivel.setText("");
            txtMarca.setText("");

            readJTable();
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        CadastrarVeiculo telaCadastrarVeiculo = new CadastrarVeiculo();
        telaCadastrarVeiculo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        int id = (int) tVeiculo.getValueAt(tVeiculo.getSelectedRow(), 0);
        String modelo = txtModelo.getText();
        String ano = txtAno.getText();
        String chassis = txtChassis.getText();
        String valorDiaria = txtVDiaria.getText();
        String capacidade = txtCapacidade.getText();
        String combustivel = txtCombustivel.getText();
        String marca = txtMarca.getText();

        Veiculo veiculo = new Veiculo(modelo, ano, chassis, valorDiaria, capacidade, combustivel, marca, id);
        VeiculoDAO v = new VeiculoDAO();

        v.alterar(veiculo);

        txtModelo.setText("");
        txtAno.setText("");
        txtChassis.setText("");
        txtVDiaria.setText("");
        txtCapacidade.setText("");
        txtCombustivel.setText("");
        txtMarca.setText("");

        readJTable();    
        
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtVDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVDiariaActionPerformed

    }//GEN-LAST:event_txtVDiariaActionPerformed

    private void tVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tVeiculoMouseClicked
        String modelo = tVeiculo.getValueAt(tVeiculo.getSelectedRow(), 1).toString();
        String ano = tVeiculo.getValueAt(tVeiculo.getSelectedRow(), 2).toString();
        String chassis = tVeiculo.getValueAt(tVeiculo.getSelectedRow(), 3).toString();
        String valorDiaria = tVeiculo.getValueAt(tVeiculo.getSelectedRow(), 4).toString();
        String capacidade = tVeiculo.getValueAt(tVeiculo.getSelectedRow(), 5).toString();
        String combustivel= tVeiculo.getValueAt(tVeiculo.getSelectedRow(), 6).toString();
        String marca = tVeiculo.getValueAt(tVeiculo.getSelectedRow(), 7).toString();
        
        txtModelo.setText( modelo);
        txtAno.setText(ano);
        txtChassis.setText(chassis);
        txtVDiaria.setText(valorDiaria);
        txtCapacidade.setText(capacidade);
        txtCombustivel.setText(combustivel);
        txtMarca.setText(marca);
        
    }//GEN-LAST:event_tVeiculoMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoVoltarTelaHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tVeiculo;
    private javax.swing.JFormattedTextField txtAno;
    private javax.swing.JTextField txtCapacidade;
    private javax.swing.JTextField txtChassis;
    private javax.swing.JTextField txtCombustivel;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtVDiaria;
    // End of variables declaration//GEN-END:variables
}
